[build]
  base      = "phase2-gather"
  publish   = "build"
  command   = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"